name: generate animation
on:
    schedule:
      - cron: "0 */24 * * *"
    workflow_dispatch:
    push:
      branches:
      - main
jobs:
    generate:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        # Generate standard snake
        - name: generate github-contribution-grid-snake.svg
          uses: Platane/snk@v3
          with:
            github_user_name: anro772
            github_token: ${{ secrets.GITHUB_TOKEN }}
            outputs: |
              dist/github-contribution-grid-snake.svg
              dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        
        # Custom step to add calendar labels to SVG
        - name: Add calendar labels to snake SVG
          run: |
            # This would require custom scripting to modify the SVG
            # Adding month and weekday labels manually to the generated SVG
            python3 -c "
            import re
            import sys
            
            # Read the generated SVG
            with open('dist/github-contribution-grid-snake.svg', 'r') as f:
                svg_content = f.read()
            
            # Add month labels (this is a simplified example)
            months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            weekdays = ['Mon', 'Wed', 'Fri']
            
            # Insert month labels - this would need actual coordinate calculation
            month_labels = ''
            for i, month in enumerate(months[:7]):  # Show 7 months
                x = 20 + (i * 15)  # Approximate positioning
                month_labels += f'<text x=\"{x}\" y=\"10\" fill=\"#586069\" font-size=\"9\">{month}</text>'
            
            # Insert weekday labels
            weekday_labels = ''
            for i, day in enumerate(weekdays):
                y = 25 + (i * 24)  # Approximate positioning
                weekday_labels += f'<text x=\"10\" y=\"{y}\" fill=\"#586069\" font-size=\"9\">{day}</text>'
            
            # Insert labels into SVG (this is a basic example - would need proper positioning)
            svg_with_labels = svg_content.replace('<svg', f'<svg>{month_labels}{weekday_labels}<svg', 1)
            
            # Write back the modified SVG
            with open('dist/github-contribution-grid-snake-with-labels.svg', 'w') as f:
                f.write(svg_with_labels)
            "
        
        # Push the content
        - name: push github-contribution-grid-snake.svg to the output branch
          uses: crazy-max/ghaction-github-pages@v3.1.0
          with:
            target_branch: output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
